# Generated by Django 5.0.7 on 2024-08-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('slug', models.CharField(max_length=200)),
                ('contents', models.TextField(verbose_name='содержимое')),
                ('publications', models.BooleanField(default=False, verbose_name='флаг публикации')),
                ('image', models.ImageField(upload_to='blog_entry/', verbose_name='превью')),
                ('views', models.IntegerField(default=0, verbose_name='просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
            },
        ),
    ]
