# Generated by Django 5.0.7 on 2024-08-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='publications',
            field=models.BooleanField(default=True, verbose_name='флаг публикации'),
        ),
    ]
