# Generated by Django 5.0.7 on 2024-08-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogentry_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
