# Generated by Django 5.0.7 on 2024-08-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogentry_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата изменения'),
        ),
    ]
