# Generated by Django 5.0.7 on 2024-08-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='massage',
            new_name='message',
        ),
    ]
