# Generated by Django 5.0.7 on 2024-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_people_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.IntegerField(verbose_name='телефон'),
        ),
    ]
